### ISSUE TITLE
frequency-based trips?

### ISSUE THREAD

**Issue by jamesdeweese** [ipeaGIT/r5r#124]
Quick question about an error I'm receiving for detailed itineraries when testing this out in Montreal:

When calling detailed_itineraries() for a "WALK" and "TRANSIT" trip between two points in Montreal, I get the following error:

> Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
>   java.lang.UnsupportedOperationException: Frequency-based trips are not yet supported in customer-facing profile routing

Does this mean that R5 is not able to route over services that use a frequencies table, e.g. Montreal's STM Metro? The travel_time_matrix() function runs without error, but does this error from detailed_itineraries() mean that the matrix results are actually excluding the possibility of travel via Metro?

(I don't think I can provide a reproducible example here given the size of the gtfs feeds and .pbf or the resulting network file, but I'm happy to share directly if necessary.)

**Comment by mvpsaraiva** [comment]
Hi @jamesdeweese. 
Indeed, currently R5 cannot provide detailed itineraries for services with frequencies tables. But you don't need to worry about the results from `travel_time_matrix()`, as they consider frequency-based services correctly. 
This happens because `detailed_itineraries()` and `travel_time_matrix()` use different algorithms. You can read about that in issue #114.

**Comment by jamesdeweese** [comment]
Thanks for quick response! Great package.
