### ISSUE TITLE
Null check for departure_datetime parameter

### ISSUE THREAD

**Issue by mattwigway** [ipeaGIT/r5r#147]
If you feed a NULL departure_datetime parameter to travel_time_matrix, it crashes with the message "java.lang.NullPointerException" and no other details. It would be great to have a null check for this parameter.

**Comment by rafapereirabr** [comment]
Thanks for the heads up. As it stands, the routing functions in `r5r` set `departure_datetime = Sys.time()` by default. Nonetheles, the functions were throwing an error because the time zone information was missing. I've fixed this so that `r5r` now considers the user's time zone by default. See reprex below.

As an alternative, the user can set a different time zone using: `as.POSIXct("13-05-2019 14:00:00", format = "%d-%m-%Y %H:%M:%S", tz="UTC")`


Reprex:
```
library(r5r)

# build transport network and load origin/destination points
data_path <- system.file("extdata/spo", package = "r5r")
r5r_core <- setup_r5(data_path = data_path)
points <- read.csv(file.path(data_path, "spo_hexgrid.csv"))[1:5,]

ttm <- travel_time_matrix(r5r_core,
                   origins = points,
                   destinations = points,
                   mode = c("WALK"),
                   max_walk_dist = Inf,
                   max_trip_duration = 120L)

```

**Comment by mattwigway** [comment]
Wouldn't it be better to use the transport network's time zone? Otherwise results from identical code could change depending on where the user is.
