### ISSUE TITLE
Cannot run setup_r5

### ISSUE THREAD

**Issue by tingli21** [ipeaGIT/r5r#217]
When I run setup_r5, I get the following error:

_Error in curl::curl_fetch_memory(url, handle = handle) : 
SSL certificate problem: unable to get local issuer certificate_

When I add these lines in:
library(httr)
httr::set_config(config(ssl_verifypeer = 0L))

I get another error:

Error in utils::download.file(url = metadata_link, destfile = metadata_file,  : 
  cannot open URL 'https://www.ipea.gov.br/geobr/r5r/metadata.csv'

Is this a problem with the server or my connection? Tried a local wifi network and an edu vpn connection.

**Comment by rafapereirabr** [comment]
Hi @tingli21 . This was a temporary problem on our data server. This should be fixed now. Could you please let us know if the problem persist?

**Comment by rafapereirabr** [comment]
Have you tried restarting your R session ?

**Comment by tingli21** [comment]
Yes I have tried multiple times

**Comment by rafapereirabr** [comment]
I've checked our servers and everything seems to be working fine. I suspect your network might be blocking the connection to our server. Could you please try doing this from another internet network? obs. Are you trying to do this connected to **eduroam**?

**Comment by mvpsaraiva** [comment]
Hi @tingli21. Are you still getting the same problem? The latest development version of `r5r` has a fix for SSL issues on Linux machines, perhaps it can help. Just install it from GitHub:

```R
  devtools::install_github("ipeaGIT/r5r", subdir = "r-package")
```

**Comment by jbroach** [comment]
I'm also experiencing this issue, and it looks like the data server is down again (no response to ping since Feb 4). What's the reason for hitting the remote server on initial setup instead of providing the .jar files with the package? Is there any risk to just copying over the .jar files from a previous install (same version)?

**Comment by mvpsaraiva** [comment]
Hi @jbroach. Indeed, the data server is down this weekend for maintenance. It should be back up tomorrow. 
We can't include R5's jar into the package because it's a 46MB file, and CRAN limits package sizes to 5MB. You can copy it from a previous install or from another computer, it should work just fine if it's saved in the correct folder and with the same name.

**Comment by rafapereirabr** [comment]
Hi all. We just published a new verion of r5r v0.7.0 on CRAN. This issue should be fixed with this new version.

**Comment by ansoncfit** [comment]
For future reference, r5 .jars are available as Conveyal-built packages. See https://github.com/ipeaGIT/r5r/issues/226#issuecomment-1036416426

**Comment by rafapereirabr** [comment]
Closing this issue for now, but please let us know if the problem persists on your side.
