### ISSUE TITLE
detailed_itineraries and travel_time_matrix return different total travel times

### ISSUE THREAD

**Issue by FlxPo** [ipeaGIT/r5r#257]
Hi,

First of all I'd like to thank all the developpers of this package, it makes a lot of the gruntwork disappear (preparing osm files, ingesting GTFS...) and opens a lot of new possibilities directly in R (multi modal routing !).

I'm not sure if this is a bug or a misunderstanding on my part, but I was surprised to find that the travel_time_matrix and detailed_itineraries return quite different travel times between the same origin/destination points.

Am I missing something ?

Here is a short reproducible example :

```r
library(r5r)
library(sf)
library(data.table)

data_path <- system.file("extdata/poa", package = "r5r")

poi <- fread(file.path(data_path, "poa_points_of_interest.csv"))
points <- fread(file.path(data_path, "poa_hexgrid.csv"))
sampled_rows <-  sample(1:nrow(points), 200, replace=TRUE)
points <- points[ sampled_rows, ]

r5r_core <- setup_r5(data_path = data_path, verbose = TRUE)

# calculate a travel time matrix
ttm <- travel_time_matrix(r5r_core = r5r_core,
                          origins = points[1],
                          destinations = points[2],
                          mode = "CAR")

# calculate detailed itineraries
det <- detailed_itineraries(r5r_core = r5r_core,
                            origins = points[1],
                            destinations = points[2],
                            mode = "CAR",
                            shortest_path = TRUE)


print(ttm$travel_time)
print(det$total_duration)

stop_r5(r5r_core)
rJava::.jgc(R.gc = TRUE)

```

**Comment by FlxPo** [comment]
OK, but shouldn't detailed_itineraries return the optimal (fastest) path along suboptimal ones ?
Or do the heuristics change the results ?

**Comment by FlxPo** [comment]
OK, I get it, I'll stick to travel_time_matrix for now. Thanks for taking the time to explain and illustrate the differences !

It would be great if travel_time_matrix could return distances also (as asked here : https://github.com/ipeaGIT/r5r/issues/261). I tried to dig into the java code, but I don't know enough about R5 for now to see if it's possible.

**Comment by mvpsaraiva** [comment]
> It would be great if travel_time_matrix could return distances also (as asked here : #261). I tried to dig into the java code, but I don't know enough about R5 for now to see if it's possible.

As i've mentioned in #261, R5 is mostly built around minimising travel times, not distances. But the functionality for calculating travel distances is kind of there, deeply buried. For example, the `StreetRouter` class, that does the walk/cycle/car routing, has an option to choose between minimising times or distances [here](https://github.com/conveyal/r5/blob/600b9ffc588ee2183b689acc215bd885708c4c1f/src/main/java/com/conveyal/r5/streets/StreetRouter.java#L114).  However, the `TravelTimeComputer` class, that does the heavy lifting of calculating travel times in multimodal networks, hardwires `StreetRouter` into evaluating travel times instead of distances [here](https://github.com/conveyal/r5/blob/600b9ffc588ee2183b689acc215bd885708c4c1f/src/main/java/com/conveyal/r5/analyst/TravelTimeComputer.java#L167).

So, technically, it is possible to fork R5 and create a sort of `TravelDistanceComputer` to do the job. Or at least use `StreetRouter` directly to calculate travel distances by walk/bike/car, without the public transport component.

**Comment by mvpsaraiva** [comment]
Anyways, if you really need to operate on distances for non-transit transport modes, I suggest using [dodgr](https://github.com/ATFutures/dodgr).

**Comment by FlxPo** [comment]
Yes I'm already using dodgr for unimodal routing ! I got really excited when I saw r5r could handle uni AND multi modal calculations...

I think I'll use r5r for multi modal routing only, with the detailed_itineraries function to get both time and distance travelled by mode.

Thanks !

**Comment by rafapereirabr** [comment]
closing this issue for now.
