### ISSUE TITLE
Walk/Bike/Drive distance as breakdown stat in travel time matrix

### ISSUE THREAD

**Issue by randl068** [ipeaGIT/r5r#261]
I'm wondering if it would be at all possible to have breakdown stats as distances in addition to the existing time-based breakdowns available in the travel_time_matrix function. On a similar note, a way to specify max driving distance could also be useful but understandably a more complex ask.

**Comment by mvpsaraiva** [comment]
Hi @randl068. 
In `r5r`, we only pass along information that R5 produces, which are restricted to travel times. Changing this logic to travel distances would require significant changes upstream in R5, and I'm sure this is not on Conveyal's radar.
You can get rough estimates of travel distances by multiplying travel times and speed of each mode, but that would not account for more complex behaviours such as when a cyclist decides to dismount the bike to cross a busy street or go up some stairs (which actually happen internally in R5 routing engine). It also would not account for the effect of topography #243.
Travel distances by car are even more difficult, because each street segment has its own max speed, and that's precisely why we can't have a max driving distance parameter in `r5r`, but a max driving time would be possible (this is more or less covered by `max_trip_duration`).
