### ISSUE TITLE
travel_time_matrix computation for many and very distant POIs fails after a few iteration

### ISSUE THREAD

**Issue by rekubi** [ipeaGIT/r5r#279]
The computation of the travel time matrix for 7904 POI on the Italian OSM road network starts and then fails after a few iterations (5 or 6 out of 7904). The calculation includes origins and destinations on islands, meaning they are not reachable using the car from the mainland. The error raised is the following:

_org.geotools.referencing.factory.DeferredAuthorityFactory disposeBackingStore
INFO: Disposing class org.geotools.referencing.factory.epsg.hsql.ThreadedHsqlEpsgFactory backing store
org.hsqldb.persist.Logger logInfoEvent
INFO: Database closed
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  :
  java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space_

We currently use a server with 64GB of RAM to perform the computation. 

So far, we have come up with two hypotheses on the issue:
- We need more powerful machines 
- The library fails to manage origins and destinations on the mainland and islands.

### Reproducible example here
```r
rm(list=ls())
options(java.parameters = c("-XX:+UseConcMarkSweepGC", "-Xmx64g"))
gc()

library(r5r)

# build transport network
data_path <- system.file("extdata/poa", package = "r5r")  
# our data path contains both the OSM road network (.pbf) and GTFS in .zip format. The GTFS refers to only a small portion of the whole Italian country, but POIs are spare over the whole country
 
r5r_core <- setup_r5(data_path = data_path, verbose = FALSE)

# load origin/destination points
points <- read.csv(file.path(data_path, "poa_hexgrid.csv"))

mode = c('CAR') # only travel time by car
max_trip_duration = 1440 # max 24 hours travel time
departure_datetime = as.POSIXct('21-04-2022', format = '%d-%m-%Y') # N.B. deleted the hour, passed only the date

### TRAVEL TIME COMPUTATION ###########
ttm = travel_time_matrix(
  r5r_core,
  origins = points ,
  destinations = points ,
  mode = mode,
  departure_datetime = departure_datetime,
  max_trip_duration = max_trip_duration,
  verbose = FALSE
)

**Comment by mvpsaraiva** [comment]
Hi @rekubi. If your inputs include the entire road network of Italy, then I suspect 64GB of RAM will not be enough. We use twice that amount to run São Paulo smoothly. I don't think the islands are a problem, because the error message specifically mentions memory issues.

I can think of two things you can try. First, reduce the number of concurrent threads through the `n_threads` parameter. The logic is that if you have fewer things running simultaneously at any given time, then you won't need as much memory.

The second thing you can try is using the `output_dir` parameter, which is available in the current development version of `r5r` on GitHub. If you point `output_dir` to an existing folder, `r5r` will save one csv file per origin POI in that folder instead of loading the full travel time matrix to memory.

**Comment by rekubi** [comment]
Hi @mvpsaraiva , thanks a lot!

We'll give a shot with the tuning you suggested. I'll keep you posted on the outcome.

**Comment by rafapereirabr** [comment]
Hi @rekubi , any success in your new attempt ?

**Comment by rafapereirabr** [comment]
Hi @rekubi .  I'm closing this for now but feel free to reopen the issue if the problem persists.
