### ISSUE TITLE
Simple question about travel_time_matrix computation

### ISSUE THREAD

**Issue by rekubi** [ipeaGIT/r5r#293]
Hello!

I have a simple - maybe silly - question about the computation of the travel time matrix by car, given a set of origin and destination points.  I understood that the travel time is computed using the maximum speed set by OSM in the road network. I was wondering how the path is selected; is it the shortest path between each origin and destination considering the maximum speed?

The main doubt behind the question is that the computed travel times by car between the same origins and destinations increase (often, they are tiny increments) considering more updated OSM networks. As the traffic component does not affect the computations, it is unexpected to experience such increases. The network should be more 'connected' as the years pass.

Thanks for your patience!

Best,

Francesco

**Comment by rekubi** [comment]
The main doubt behind the question is that the computed travel times by car between the same origins and destinations increase (often, they are tiny increments) considering more updated OSM networks. As the traffic component does not affect the computations, it is unexpected to experience such increases. The network should be more 'connected' as the years pass.

**Comment by rafapereirabr** [comment]
Hi @rekubi . Thank you for your question. Yes, `R5`and hence `r5r` will return shortest path by car considering the max speed allowed in each road segment.

It's hard to know exactly what could be causing these tiny increments. It could be due to differences between the different files of OpenStreetMap data you're using. This could be, for example because the speed limits recorded for specific road segments have changed, or because recent versions of the OSM data have better data coverage and include more road segments. In the latter case, this could affect the location where the origin and destination points of the trips are snapped to the road network

**Comment by rafapereirabr** [comment]
closing this issue for.
