### ISSUE TITLE
Use other routable transport network than osm

### ISSUE THREAD

**Issue by jkaucic** [ipeaGIT/r5r#320]
Is it possible to use another transport network than osm to create isochrones with r5r? I will get a network layer from Here with historical traffic data (speeds) and was wondering if I can use this in r5r - possibly by adapting its data structure to that of osm. Thank you

**Comment by rafapereirabr** [comment]
Hi @jkaucic . R5 and hence r5r only works with OpenStreetMap data in `.pbf` format. If you can pass the speed information from your data set to a local `.pbf` file, you could probably the historical speed in r5r. This might not me trivial though. See issue #289. Closing this issue because it's been covered in 289.
