### ISSUE TITLE
Odd combinations of transport modes

### ISSUE THREAD

**Issue by mvpsaraiva** [ipeaGIT/r5r#63]
Our heuristic for turning one parameter `mode` into the 4 parameters R5 uses (direct_mode, transit_mode, access_mode and egress_mode) sometimes generates odd path options. For example, should we consider options such as driving to the bus stop, then taking the bus, and then driving again to the destination? 

Example:

```
library("r5r")
library("ggplot2")

# Start R5R core
r5r_core <- setup_r5(system.file("extdata", package = "r5r"), verbose = FALSE)

# Load points of interest
points <- read.csv(system.file("extdata/poa_points_of_interest.csv", package = "r5r"))


# Configuring trip
origin <- points[10,] # Farrapos train station
destination <- points[12,] # Praia de Belas shopping mall

trip_date_time <- lubridate::as_datetime("2019-03-20 14:00:00")

max_walk_distance = 0.8
max_trip_duration = 120L

paths_df <- detailed_itineraries(r5r_core = r5r_core,
                                 origins = origin, destinations = destination,
                                 departure_datetime = trip_date_time,
                                 max_walk_dist = max_walk_distance,
                                 max_trip_duration = max_trip_duration,
                                 mode = c("WALK", "BICYCLE", "CAR", "BUS"),
                                 shortest_path = FALSE, verbose = FALSE)

paths_df %>%
  ggplot() +
  geom_sf(aes(colour=mode)) +
  facet_wrap(~option)
```

**Comment by dhersz** [comment]
I have added a quick and (hopefully) temporary fix to this. Now in the case the algorithm selects CAR and BICYCLE as possible egress modes, those are removed in the end.

I'm leaving this issue open because we have to understand some nuances of the modes better to refine `select_mode`:

- Does access and egress mode impact direct trips at all? What if a car is parked somewhere and the person needs to walk to the park?
- What's the difference between CAR + TRANSIT trips and CAR_PARK?
- Max drive and bike distance are set by specific parameters: `max_drive_distance` and `max_bike_distance` (or something like that). Those are not changed anywhere in our functions, so I think we should look at them if we plan to allow CAR and BIKE acess/egress legs.

**Comment by dhersz** [comment]
A bit of research on the modes:

#### DIRECT MODES

- CAR, BICYCLE, WALK

#### ACCESS MODES

- CAR, BICYCLE, WALK, BICYCLE_RENT, CAR_PARK

#### EGRESS MODES

- CAR, BICYCLE, WALK, BICYCLE_RENT ([CAR_PARK is not supported](https://github.com/ipeaGIT/r5r/blob/4ed7da1c6bf59afd0ed920189d441cd2fc67ffae/java-r5/src/main/java/com/conveyal/r5/point_to_point/builder/PointToPointQuery.java#L60))

### BICYCLE_RENT 

To use BICYCLE_RENT, we have to:

 - Place a .xml with bike stations info inside the graph directory and add/edit the "bikeRentalFile" field in the build-config.json with:
  
   - "bikeRentalFile" : "bikeStations.xml" (or whatever name chosen) (I'm also not sure about the specifications of this file)

 - There's also the "staticBikeRental" field in the build-config.json, which would allow us to read the bike rent stations from OSM instead of the .xml. The field defaults to "false" (which means it reads from xml), so changing it to "true" would suffice our needs, but this field is not used anywhere in the java code. 

### CAR_PARK

OSM ways and nodes must have tag [`"park_ride"`](https://github.com/ipeaGIT/r5r/blob/4ed7da1c6bf59afd0ed920189d441cd2fc67ffae/java-r5/src/main/java/com/conveyal/r5/streets/StreetLayer.java#L286). Glimpsed through some garages and parking spots located within our sample pbf and I don't think any of them have it, so we'll need to find some data to test this.

Time to stop with CAR_PARK mode [equals to](https://github.com/ipeaGIT/r5r/blob/4ed7da1c6bf59afd0ed920189d441cd2fc67ffae/java-r5/src/main/java/com/conveyal/r5/analyst/TravelTimeComputer.java#L221):

- Time by car to park + time to park + time to walk from park to stop

### BICYCLE_RENT and CAR_PARK costs

These can be found [here](https://github.com/ipeaGIT/r5r/blob/4ed7da1c6bf59afd0ed920189d441cd2fc67ffae/java-r5/src/main/java/com/conveyal/r5/point_to_point/builder/PointToPointQuery.java).

**Comment by rafapereirabr** [comment]
I've done some tests (see primary input below). These are the trave time estimates for the following combination of modes:

:walking: = **154 minutes**
'direct_modes' = "WALK"
'transit_mode' = ""
'access_mode'  = "WALK"
'egress_mode'  = "WALK"

 :walking: + :bus: + :walking: = **66 minutes**
'direct_modes' = "WALK"
'transit_mode' = "TRANSIT..."
'access_mode'  = "WALK"
'egress_mode'  = "WALK"

 :walking: + :bus: + :car: =  **28 minutes**
'direct_modes' = "WALK"
'transit_mode' = "TRANSIT..."
'access_mode'  = "WALK"
'egress_mode'  = "CAR"

:car: + :bus: + :walking: = **18 minutes**
'direct_modes' = "CAR"
'transit_mode' = "TRANSIT..."
'access_mode'  = "CAR"
'egress_mode'  = "WALK"

:car: + :bus: + :car: = **18 minutes**
'direct_modes' = "CAR"
'transit_mode' = "TRANSIT..."
'access_mode'  = "CAR"
'egress_mode'  = "CAR"








**Primary input:**
```
# load origin/destination points
data_path <- system.file("extdata/poa", package = "r5r")
points <- read.csv(file.path(data_path, "poa_hexgrid.csv"))
r5r_core <- setup_r5(data_path = data_path)
departure_datetime <- as.POSIXct("13-05-2019 14:00:00", format = "%d-%m-%Y %H:%M:%S")


# estimate travel time matrix
travel_time_matrix(r5r_core,
                          origins = points[120,],
                          destinations = points[10,],
                          departure_datetime = departure_datetime,
                          max_walk_dist = Inf,
                          max_trip_duration = 1200L)

# variations of mode combinations
mode_list <- list('direct_modes' = "WALK",
                  'transit_mode' = "TRANSIT;TRAM;SUBWAY;RAIL;BUS;FERRY;CABLE_CAR;GONDOLA;FUNICULAR",
                  'access_mode'  = "WALK",
                  'egress_mode'  = "WALK")

```
